version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    env_file:
      - .env
    ports:
      - 3002:3000
    tty:
      true # コンテナを起動させたままにする
    volumes:
      - ./src:/src
